version: '3.8'

services:
  listing-service:
    build:
      context: ./listing-service
    environment:
      DB_DRIVER: sqlite3
      DB_PATH: /app/data/listing-service.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
  
  user-service:
    build:
      context: ./user-service
    environment:
      DB_DRIVER: sqlite3
      DB_PATH: /app/data/listing-service.db
    volumes:
      - ./data:/app/data
    networks:
      - app-network
  
  public-api:
    build:
      context: ./public-api
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge